image: docker:latest

variables:
  REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: registry.gitlab.com/radtriste/vente-meuble/website
  DIST_FOLDER: dist

stages:
- build
- deploy

services:
  - docker:dind

build:image:
  stage: build
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  - chmod u+x generate.sh
  script:
  - export GENERATION_COMMAND_PREFIX="docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor " && ./generate.sh
  - docker build --build-arg DIST_FOLDER=$DIST_FOLDER -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
  - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA


##################################################
## Deploy

deploy:tag_image:
  stage: deploy
  before_script:
  - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN:-$CI_JOB_TOKEN}" $REGISTRY
  script:
  - docker pull $DOCKER_IMAGE:$CI_COMMIT_SHA
  - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
  - docker push $DOCKER_IMAGE:latest
  only:
  - master